### ISSUE TITLE
Improvement of the propagation sync (ordered messages)

### ISSUE THREAD

**Issue by SebastianObi** [markqvist/LXMF#14]
It would be good if the transfer of messages would not be randomly mixed like now but would be "first in first out" or "last in first out" based on the timestamp. 

Then additionally as a parameter like the limit which the client sends to the propagation node. The limit makes no sense if the messages are transmitted in a random way. 

This would also improve the message processing in the client apps.

**Comment by markqvist** [comment]
This is not possible, per se, since everything is encrypted, and LXMF propagation nodes have no idea about any of the metadata.

The messages are not transmitted in a "random way". LXMF prioritises messages based on several things, but one very important aspect is message size, with small messages being prioritised higher than large.

Small messages are always prioritised over large messages, since a message containing "We are alive" is a lot more important than a 200 KB cat meme ;)

The right way to implement user-centric sorting is in the client, where messages are displayed to a user.

**Comment by markqvist** [comment]
This is not possible, per se, since everything is encrypted, and LXMF propagation nodes have no idea about any of the metadata.

The messages are not transmitted in a "random way". LXMF prioritises messages based on several things, but one very important aspect is message size, with small messages being prioritised higher than large.

Small messages are always prioritised over large messages, since a message containing "We are alive" is a lot more important than a 200 KB cat meme ;)

The right way to implement user-centric sorting is in the client, where messages are displayed to a user.
